#!/usr/bin/env python3
"""Regenerate the post-layout (extracted-netlist) DUT binding for simulation
-- issue #23 (T1 checklist item 7, post-layout simulation).

WHAT THIS SCRIPT DOES
----------------------
1. `klt extract layout/comparator.gds --deck gf180mcu --top COMPARATOR
   --pins <the 8 interface nets> --parasitics` -- the same extraction
   `layout/run_lvs.py` issues for LVS (#22), plus `--parasitics` so the
   written netlist additionally carries first-order lumped RC parasitics
   (one series R per net terminal, one ground C per net, plus vertical-
   overlap coupling capacitors between nets -- the `klt extract --help`
   text describes the exact model). Writes the raw extracted netlist to
   `layout/lvs/comparator.extracted-rc.spice` (scratch, `.gitignore`'d --
   same rule and same reason as run_lvs.py's own extracted netlist:
   anonymous net numbering is not a stable contract across klayout
   versions/hosts) and the structured JSON report to
   `layout/lvs/comparator.extract-rc.json` (committed evidence).

2. Adapts that raw netlist into the simulation DUT binding
   `layout/lvs/comparator.dut-layout.spice` (scratch, `.gitignore`'d),
   which `sim/dut.json`'s `comparator-dr0001-layout` entry binds. Two
   adaptations, both mechanical:

   a. DEVICE PRIMITIVES. `klt extract` writes devices under the extraction
      deck's own class names -- bare MOS model cards (`M... nfet`) and
      semiconductor-resistor cards (`R... <value> ppolyf_u_1k L= W=`) --
      because those are the names its LVS deck defines. The installed
      ngspice models instead expose 3.3 V devices as the subcircuit
      wrappers `nfet_03v3` / `pfet_03v3` / `ppolyf_u_1k` (see
      `sim/harness/pdk.py`'s model_lib). This script rewrites each device
      card onto its simulation primitive, using exactly the class-to-
      subcircuit correspondence `layout/run_lvs.py`'s
      `DEVICE_GEOMETRY_MAP` already asserts at LVS time -- the mapping is
      verified evidence (#22), not a new assumption. The resistor rewrite
      converts the extraction's computed absolute value + L/W into the
      PDK subckt call form (`XR... a b sub ppolyf_u_1k r_length= r_width=
      m=1`), so the resistor stays corner-aware (`res_typical`/`res_ff`/
      `res_ss` sections) exactly as the schematic netlist's own resistors
      are, instead of freezing the nominal extraction-time value.

   b. INTERFACE WRAPPER. The extraction's flat top cell is `COMPARATOR`
      (uppercase, the GDS cell name). The harness's DUT interface contract
      (sim/dut/README.md, asserted textually by sim/harness/dut.py)
      requires `.subckt comparator_dut vinp vinn clk ibias dout doutb vdd
      vss` in exactly that pin order -- the same order `--pins` passes to
      `klt extract`. The adapter appends a one-line wrapper subckt that
      instantiates `COMPARATOR` under the contract name, leaving the
      extracted text itself untouched (auditable: the wrapper is visibly
      additive).

   A flat extraction cannot expose `comparator_dut_analog` /
   `comparator_dut_latch` (the schematic netlist's hierarchy is flattened
   away), so `sim/harness/dut.py` requires only `comparator_dut` from an
   `extracted`-provenance binding, and `sim/run_corners.py` refuses a bench
   whose fragment instantiates a subckt the bound DUT does not provide.

3. Asserts the adapted netlist satisfies the interface contract (same
   textual pin-order check `sim/harness/dut.py` applies at load time), and
   prints the sha256 of the adapted netlist so a record's
   `dut_netlist_sha256` can be traced back to this run's committed
   `comparator.extract-rc.json` report.

The LVS-match claim itself is NOT re-derived here: `layout/lvs/
comparator.lvs.json` (regenerated by `layout/run_lvs.py`, #22) is the
evidence that the extracted netlist matches `design/comparator.spice`.
This script's extraction adds `--parasitics` to the same layout, deck,
top cell and pin set; the parasitic block changes only R/C elements, not
device topology.

Usage
-----
    python3 layout/run_extract_sim.py

Requires `klt` on `PATH` (same toolchain pin as `layout/run_lvs.py`).
Exits non-zero when the extraction fails, the report is missing its
parasitics block, or the adapted netlist fails the interface-contract
check. Idempotent: re-running regenerates all three artifacts.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)
OUTDIR = os.path.join(HERE, "lvs")
GDS = os.path.join(HERE, "comparator.gds")

RAW_NETLIST = os.path.join(OUTDIR, "comparator.extracted-rc.spice")
EXTRACT_REPORT = os.path.join(OUTDIR, "comparator.extract-rc.json")
DUT_NETLIST = os.path.join(OUTDIR, "comparator.dut-layout.spice")

DECK = "gf180mcu"
TOP = "COMPARATOR"

#: sim/dut/README.md's interface contract, in its own declared ORDER -- the
#: same tuple `layout/run_lvs.py` passes as `--pins` (issue #514) so the
#: extracted top cell exposes exactly the pins the testbenches wire up.
INTERFACE_PINS = ("vinp", "vinn", "clk", "ibias", "dout", "doutb", "vdd", "vss")

#: The extraction-deck device class -> PDK ngspice simulation primitive
#: correspondence, restricted to the classes this layout actually instantiates
#: (comparator.extract.json's device_counts: nfet, pfet, ppolyf_u_1k). This is
#: `layout/run_lvs.py`'s DEVICE_GEOMETRY_MAP key set -- the same correspondence
#: #22's geometry assertions verify -- stated here in simulation direction.
#: A card naming a class NOT in this table is a hard failure, never a silent
#: skip: a new device family in the layout must fail this script loudly until
#: someone declares how to simulate it.
MOS_CLASS_TO_SUBCKT = {
    "nfet": "nfet_03v3",
    "pfet": "pfet_03v3",
}

#: The resistor class whose extraction cards (R... <value> <class> L= W=)
#: are rewritten into the PDK subckt call form. The subckt's parameter
#: spellings come from the PDK's own `.subckt ppolyf_u_1k` definition.
RES_CLASS = "ppolyf_u_1k"
RES_LENGTH_PARAM = "r_length"
RES_WIDTH_PARAM = "r_width"

_MOS_RE = re.compile(rf"^(M\S+)\s+(.*?\s+)({'|'.join(MOS_CLASS_TO_SUBCKT)})(\s+L=)")
_RES_RE = re.compile(
    rf"^(R\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+\S+\s+{RES_CLASS}\s+L=(\S+)\s+W=(\S+)\s*$"
)


def run_extract() -> dict:
    # cwd=REPO_ROOT and repo-relative paths so the committed report's own
    # `file`/`netlist_path` fields stay host-independent (same discipline as
    # layout/run_lvs.py's run_extract).
    cmd = [
        "klt", "extract", os.path.relpath(GDS, REPO_ROOT),
        "--deck", DECK,
        "--top", TOP,
        "--pins", ",".join(INTERFACE_PINS),
        "--parasitics",
        "-o", os.path.relpath(RAW_NETLIST, REPO_ROOT),
        "--format", "json",
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=REPO_ROOT)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        sys.exit(f"klt extract --parasitics failed (exit {proc.returncode})")
    report = json.loads(proc.stdout)
    with open(EXTRACT_REPORT, "w") as f:
        json.dump(report, f, indent=2, sort_keys=True)
        f.write("\n")
    return report


def _check_report(report: dict) -> None:
    """The parasitics block is the one thing this extraction exists to add."""
    parasitics = report.get("parasitics")
    if not isinstance(parasitics, dict) or not parasitics.get("nets"):
        sys.exit(
            f"{EXTRACT_REPORT}: extraction reports no parasitics block -- "
            "klt extract --parasitics did not do what this script exists to do"
        )
    counts = report.get("device_counts") or {}
    unknown = set(counts) - set(MOS_CLASS_TO_SUBCKT) - {RES_CLASS}
    if unknown:
        sys.exit(
            f"{EXTRACT_REPORT}: extracted device classes {sorted(unknown)} have "
            "no simulation-primitive mapping in this script -- declare how to "
            "simulate them before binding a post-layout DUT"
        )


def _extracted_top_pins() -> list[str]:
    """The pin list of the raw extraction's top cell, in ITS declared order.

    `klt extract --pins` fixes WHICH nets become pins, not their ORDER on
    the ``.SUBCKT`` line (the writer emits them alphabetically). The wrapper
    below must therefore connect positionally against the order read here,
    not against the ``--pins`` argument -- the first smoke run of this
    script wired them naively and every bench measurement came out garbage
    (outputs parked mid-rail, static current 10 uA instead of 28 uA).
    """
    pattern = re.compile(rf"^\.SUBCKT\s+{TOP}\s+(.+)$", re.IGNORECASE)
    with open(RAW_NETLIST) as f:
        for raw in f:
            m = pattern.match(raw.strip())
            if m:
                return m.group(1).split()
    sys.exit(
        f"{RAW_NETLIST}: no `.SUBCKT {TOP} ...` line found -- the extraction "
        f"did not produce the expected top cell"
    )


def _adapt_netlist() -> int:
    """Rewrite device cards onto PDK primitives and append the wrapper.

    Returns the number of rewritten device cards (printed for the record).
    """
    rewritten = 0
    out: list[str] = []
    for raw in open(RAW_NETLIST).read().splitlines():
        line = raw
        m = _MOS_RE.match(line)
        if m:
            line = (
                f"{m.group(1)} {m.group(2)}"
                f"{MOS_CLASS_TO_SUBCKT[m.group(3)]}{m.group(4)}"
                + line[m.end():]
            )
            rewritten += 1
            out.append(line)
            continue
        m = _RES_RE.match(line)
        if m:
            name, a, b, sub, length, width = m.groups()
            line = (
                f"X{name[1:]} {a} {b} {sub} {RES_CLASS} "
                f"{RES_LENGTH_PARAM}={length} {RES_WIDTH_PARAM}={width} m=1"
            )
            rewritten += 1
            out.append(line)
            continue
        out.append(line)

    top_pins = _extracted_top_pins()
    if sorted(p.lower() for p in top_pins) != sorted(INTERFACE_PINS):
        sys.exit(
            f"{RAW_NETLIST}: top cell {TOP} pins {top_pins} are not the "
            f"interface pin set {list(INTERFACE_PINS)} -- the --pins argument "
            "did not reach the extraction"
        )
    # Positional connection in the extracted declaration order: formal pin
    # top_pins[i] receives the wrapper's node named top_pins[i] (same names,
    # deliberately reordered so the mapping is name-correct AND positional).
    wrapper = (
        "\n* ---- interface wrapper (appended by layout/run_extract_sim.py) ----\n"
        f"* The extraction's flat top cell {TOP}, exposed under the harness's\n"
        "* comparator_dut interface contract (sim/dut/README.md). Additive only:\n"
        "* the extracted netlist above is untouched; the X-line connects in "
        "COMPARATOR's\n* own (alphabetical) declaration order.\n"
        f".subckt comparator_dut {' '.join(INTERFACE_PINS)}\n"
        f"Xlayout_dut {' '.join(top_pins)} {TOP}\n"
        ".ends\n"
    )
    with open(DUT_NETLIST, "w") as f:
        f.write("\n".join(out) + "\n")
        f.write(wrapper)
    return rewritten



def _check_interface_contract() -> None:
    """The same textual pin-order check sim/harness/dut.py applies at load
    time, restated here so a broken adaptation fails at generation time,
    not at the first simulated point."""
    declared: dict[str, tuple[str, ...]] = {}
    for raw in open(DUT_NETLIST).read().splitlines():
        line = raw.strip()
        if not line.lower().startswith(".subckt"):
            continue
        tokens = line.split()
        if len(tokens) < 2:
            continue
        pins = tuple(t.lower() for t in tokens[2:] if "=" not in t)
        declared[tokens[1].lower()] = pins
    got = declared.get("comparator_dut")
    if got != INTERFACE_PINS:
        sys.exit(
            f"{DUT_NETLIST}: .subckt comparator_dut pin order is "
            f"{' '.join(got or ('<missing>',))}, contract requires "
            f"{' '.join(INTERFACE_PINS)} (sim/dut/README.md 'Interface contract')"
        )


def main() -> int:
    report = run_extract()
    _check_report(report)
    rewritten = _adapt_netlist()
    _check_interface_contract()
    digest = hashlib.sha256(open(DUT_NETLIST, "rb").read()).hexdigest()
    parasitics = report["parasitics"]
    print(f"extracted + adapted post-layout DUT netlist:")
    print(f"  raw netlist : {os.path.relpath(RAW_NETLIST, REPO_ROOT)} (scratch)")
    print(f"  report      : {os.path.relpath(EXTRACT_REPORT, REPO_ROOT)} (committed evidence)")
    print(f"  DUT binding : {os.path.relpath(DUT_NETLIST, REPO_ROOT)} (scratch)")
    print(f"  devices rewritten onto PDK primitives: {rewritten}")
    print(
        "  parasitics  : "
        f"{parasitics.get('r_count')} R + {parasitics.get('c_count')} C to substrate "
        f"+ {parasitics.get('cc_count')} coupling C "
        f"({parasitics.get('total_resistance_ohm', 0):.1f} ohm, "
        f"{parasitics.get('total_capacitance_ff', 0):.1f} fF total)"
    )
    print(f"  dut netlist sha256: {digest}")
    print(
        "\nnext: python3 sim/run_corners.py <experiment> "
        "--dut comparator-dr0001-layout   (or ./sim/characterize.sh postlayout)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
