"""Deck composition and ngspice execution for one PVT point.

Ported from ``2AMLogic/gf180-sar-adc``'s ``sim/harness/runner.py``. The one
structural change is that the DUT netlist is included here, from
``sim/dut.json`` (see ``harness/dut.py`` for why). NOT ported: that module's
``mim_wrapper_subckts()``, which binds a CDAC MIM unit capacitor to the
variant's metal stack -- this block has no capacitor array.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field
from pathlib import Path

from .corners import PvtPoint
from .dut import Dut
from .pdk import Pdk
from .testbench import Testbench

NGSPICE = "ngspice"
DEFAULT_TIMEOUT_S = 600

# `print` output for a length-1 vector: "m_vos_mv = 6.9043645202e-01"
_MEAS_RE = re.compile(r"^\s*m_(\w+)\s*=\s*([-+]?[0-9.]+(?:[eE][-+]?[0-9]+)?)\s*$")
_ERROR_RE = re.compile(r"^\s*(?:Error|ERROR|Fatal|fatal error|doAnalyses:)", re.MULTILINE)


class NgspiceMissing(RuntimeError):
    pass


def ngspice_version() -> str:
    exe = shutil.which(NGSPICE)
    if not exe:
        raise NgspiceMissing(
            "ngspice not found on PATH.\n"
            "  Debian/Ubuntu: apt-get install ngspice\n"
            "  macOS:         brew install ngspice\n"
            "See sim/README.md 'Cold start'."
        )
    out = subprocess.run(
        [exe, "--version"], capture_output=True, text=True, check=False
    ).stdout
    for line in out.splitlines():
        if "ngspice-" in line:
            return line.strip().lstrip("* ").strip()
    return out.strip().splitlines()[0] if out.strip() else "unknown"


def compose_deck(
    tb: Testbench,
    pdk: Pdk,
    dut: Dut,
    point: PvtPoint,
    num_threads: int = 0,
    extra_params: dict[str, float] | None = None,
) -> str:
    """Build the complete, self-contained ngspice deck for one PVT point.

    ``num_threads`` (0 = leave ngspice's default alone) emits ``set
    num_threads=N`` at the top of the control block. It is a **scheduling**
    knob, not a circuit one: an OpenMP-built ngspice defaults to one thread
    per processor, which on a busy host makes several concurrent points
    fight over the same cores and burn most of their CPU in OpenMP
    spin-waits. Grid throughput comes from ``-j``, not from ngspice's
    internal threads.

    ``extra_params`` are emitted as ``.param`` lines between the DUT
    operating-point params and the testbench params -- the per-PVT-point
    offset-probe result (``dut_vos``, issue #23) rides here. The deck, not
    the fragment, owns them: a fragment references ``dut_vos`` in
    expressions and never defines it, so the harness's value (0 for a
    schematic DUT, the probed offset for an extracted one) is the only
    definition the deck ever carries.
    """
    lines: list[str] = [
        f"* {tb.name} @ {point.corner_id} -- GENERATED by sim/harness, do not edit",
        f"* corner={point.corner.name} ({point.corner.description})",
        f"* temp={point.temp_c} C  vdd={point.vdd} V  pdk={pdk.variant}@{pdk.version}",
        f"* dut={dut.dut_id} ({dut.provenance})  sha256={dut.netlist_sha256[:16]}",
        "",
        "* ---- PVT parameters -------------------------------------------------",
        f".param vdd_nom={tb.nominal_supply_v!r}",
        f".param vdd_val={point.vdd!r}",
        f".param temp_c={point.temp_c!r}",
        "",
        "* ---- DUT operating-point parameters (sim/dut.json) -------------------",
        *dut.param_lines(),
    ]
    if extra_params:
        lines += [
            "",
            "* ---- per-point measured parameters (offset probe, issue #23) --------",
        ]
        for key, value in sorted(extra_params.items()):
            lines.append(f".param {key}={value!r}")
    if tb.params:
        lines += ["", "* ---- testbench parameters -------------------------------------------"]
        for key, value in tb.params.items():
            lines.append(f".param {key}={value}")

    lines += [
        "",
        "* ---- gf180mcu models ------------------------------------------------",
        f'.include "{pdk.design_include}"',
    ]
    for section in point.corner.sections:
        lines.append(f'.lib "{pdk.model_lib}" {section}')

    lines += [
        "",
        f".temp {point.temp_c!r}",
    ]
    for option in tb.options:
        lines.append(f".options {option}")

    lines += [
        "",
        "* ---- device under test (sim/dut.json) --------------------------------",
        f'.include "{dut.netlist}"',
        "",
        "* ---- testbench ------------------------------------------------------",
        f'.include "{tb.netlist}"',
        "",
        "* ---- measurement ----------------------------------------------------",
        ".control",
        "set numdgt=10",
        "set noaskquit",
    ]
    if num_threads:
        lines.append(f"set num_threads={num_threads}")
    lines += [f"  {analysis}" for analysis in tb.analyses]
    for name, expr in tb.measure.items():
        lines.append(f"  let m_{name} = {expr}")
    for name in tb.measure:
        lines.append(f"  print m_{name}")
    lines += [".endc", ".end", ""]
    return "\n".join(lines)


@dataclass
class PointResult:
    point: PvtPoint
    status: str                                   # "ok" | "failed" | "error"
    measurements: dict[str, float] = field(default_factory=dict)
    missing: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    seconds: float = 0.0
    deck: str = ""
    log: str = ""
    message: str = ""

    def as_dict(self) -> dict:
        record = self.point.as_dict()
        record.update(
            {
                "status": self.status,
                "measurements": self.measurements,
                "seconds": round(self.seconds, 3),
                "deck": self.deck,
                "log": self.log,
            }
        )
        if self.missing:
            record["missing_measurements"] = self.missing
        if self.warnings:
            record["warnings"] = self.warnings
        if self.message:
            record["message"] = self.message
        return record


def parse_measurements(text: str) -> dict[str, float]:
    found: dict[str, float] = {}
    for line in text.splitlines():
        match = _MEAS_RE.match(line)
        if match:
            try:
                found[match.group(1)] = float(match.group(2))
            except ValueError:  # pragma: no cover - regex already constrains this
                continue
    return found


def _run_offset_probe(
    probe_tb: Testbench,
    pdk: Pdk,
    dut: Dut,
    point: PvtPoint,
    workdir: Path,
    log_dir: Path,
    timeout_s: int,
    num_threads: int,
) -> float | None:
    """Run the offset probe at this PVT point; return ``dut_vos`` in volts.

    The probe's raw ngspice output is committed evidence alongside the main
    log as ``<corner-id>.vosprobe.log``. Returns None when the probe fails
    to produce the measurement (caller fails the point with a message).
    """
    deck_path = workdir / f"{point.corner_id}.vosprobe.spice"
    log_path = log_dir / f"{point.corner_id}.vosprobe.log"
    deck_path.write_text(
        compose_deck(probe_tb, pdk, dut, point, num_threads=num_threads)
    )
    try:
        proc = subprocess.run(
            [NGSPICE, "-b", str(deck_path)],
            capture_output=True, text=True, timeout=timeout_s, cwd=workdir,
            check=False,
        )
        output = proc.stdout + "\n" + proc.stderr
    except subprocess.TimeoutExpired:
        log_path.write_text(f"TIMEOUT after {timeout_s}s\n")
        return None
    log_path.write_text(output)
    measurements = parse_measurements(output)
    vos = measurements.get("dut_vos")
    return float(vos) if vos is not None else None


def run_point(
    tb: Testbench,
    pdk: Pdk,
    dut: Dut,
    point: PvtPoint,
    workdir: Path,
    timeout_s: int = DEFAULT_TIMEOUT_S,
    log_dir: Path | None = None,
    num_threads: int = 0,
    probe_tb: Testbench | None = None,
) -> PointResult:
    """Simulate one PVT point. Never raises for simulation failure.

    ``workdir`` holds the generated deck (scratch, disposable). ``log_dir``
    -- when given -- is where the raw ngspice output lands as
    ``<corner-id>.log``; that is the ``sim/<slug>/corners/<record-id>/``
    directory from ``sim/README.md``. It defaults to ``workdir`` so a
    throwaway run does not touch the evidence tree.

    ``probe_tb`` (issue #23), when given, is run FIRST at the same PVT
    point: a tiny offset-probe deck whose ``dut_vos`` measurement is the
    DUT's deterministic systematic input-referred offset. The probed value
    is injected into the main deck as ``dut_vos`` (so an offset-declaring
    fragment's overdrive ladder is referred to the comparator's own trip
    point, the gf180-sar-adc post-layout convention), stamped into the
    point's measurements as ``dut_vos_v`` for the record, and its raw
    ngspice output lands next to the main log as
    ``<corner-id>.vosprobe.log``. A probe that fails to produce ``dut_vos``
    fails the point -- an un-referral ladder on an offset-carrying DUT is a
    wrong measurement, not a degraded one.
    """
    workdir.mkdir(parents=True, exist_ok=True)
    log_dir = workdir if log_dir is None else log_dir
    log_dir.mkdir(parents=True, exist_ok=True)
    deck_path = workdir / f"{point.corner_id}.spice"
    log_path = log_dir / f"{point.corner_id}.log"

    extra_params: dict[str, float] = {}
    if getattr(tb, "offset_probe", None):
        # The fragment references dut_vos but never defines it (the harness
        # owns it); a run without a probe -- a schematic DUT, offset-free by
        # construction -- still must define it for the expressions to parse.
        extra_params["dut_vos"] = 0.0
    if probe_tb is not None:
        probed = _run_offset_probe(probe_tb, pdk, dut, point, workdir, log_dir,
                                   timeout_s, num_threads)
        if probed is None:
            return PointResult(
                point=point,
                status="failed",
                deck=deck_path.name,
                log=f"{point.corner_id}.vosprobe.log",
                message=(
                    "offset probe produced no dut_vos measurement -- the "
                    "overdrive ladder cannot be referred (offset outside the "
                    "probe's ramp range, or the probe deck failed)"
                ),
            )
        extra_params["dut_vos"] = probed

    deck_path.write_text(
        compose_deck(tb, pdk, dut, point, num_threads=num_threads,
                     extra_params=extra_params or None)
    )

    started = time.monotonic()
    try:
        proc = subprocess.run(
            [NGSPICE, "-b", str(deck_path)],
            capture_output=True,
            text=True,
            timeout=timeout_s,
            cwd=workdir,
            check=False,
        )
        output = proc.stdout + "\n" + proc.stderr
        returncode = proc.returncode
    except FileNotFoundError as exc:
        raise NgspiceMissing(str(exc)) from exc
    except subprocess.TimeoutExpired:
        elapsed = time.monotonic() - started
        log_path.write_text(f"TIMEOUT after {timeout_s}s\n")
        return PointResult(
            point=point,
            status="error",
            seconds=elapsed,
            deck=deck_path.name,
            log=log_path.name,
            message=f"ngspice timed out after {timeout_s}s",
        )
    elapsed = time.monotonic() - started
    log_path.write_text(output)

    measurements = parse_measurements(output)
    if probe_tb is not None:
        # Stamp the probed offset into the point's evidence (as a volt
        # quantity -- the same number the main deck's dut_vos param carries).
        measurements["dut_vos_v"] = extra_params["dut_vos"]
    missing = [name for name in tb.measure if name not in measurements]

    # Computed unconditionally -- previously this returncode/_ERROR_RE scan
    # only ran inside the `if missing:` branch below, so a non-fatal ngspice
    # error (non-zero exit, or an Error/Fatal/doAnalyses: line) was silently
    # discarded whenever every requested measurement still happened to parse
    # (#7). `warnings` surfaces that finding on the "ok" path too, without
    # changing the point's status.
    error_lines = [line.strip() for line in output.splitlines() if _ERROR_RE.match(line)]
    warnings: list[str] = []
    if returncode != 0:
        warnings.append(f"ngspice exited {returncode}")
    warnings.extend(error_lines[:5])

    if missing:
        errors = "; ".join(_ERROR_RE.findall(output)[:3])
        first_error = error_lines[0] if error_lines else ""
        return PointResult(
            point=point,
            status="failed",
            measurements=measurements,
            missing=missing,
            warnings=warnings,
            seconds=elapsed,
            deck=deck_path.name,
            log=log_path.name,
            message=first_error or errors or f"ngspice exit {returncode}, no measurements parsed",
        )

    return PointResult(
        point=point,
        status="ok",
        measurements=measurements,
        warnings=warnings,
        seconds=elapsed,
        deck=deck_path.name,
        log=log_path.name,
    )


def run_grid(
    tb: Testbench,
    pdk: Pdk,
    dut: Dut,
    points: list[PvtPoint],
    workdir: Path,
    jobs: int = 1,
    timeout_s: int = DEFAULT_TIMEOUT_S,
    on_result=None,
    log_dir: Path | None = None,
    num_threads: int = 0,
    probe_tb: Testbench | None = None,
) -> list[PointResult]:
    """Run every PVT point; results come back in grid order regardless of jobs."""
    results: list[PointResult | None] = [None] * len(points)

    def _one(index_point):
        index, point = index_point
        result = run_point(
            tb, pdk, dut, point, workdir, timeout_s=timeout_s, log_dir=log_dir,
            num_threads=num_threads, probe_tb=probe_tb,
        )
        results[index] = result
        if on_result is not None:
            on_result(result)
        return result

    if jobs <= 1:
        for item in enumerate(points):
            _one(item)
    else:
        with ThreadPoolExecutor(max_workers=jobs) as pool:
            list(pool.map(_one, enumerate(points)))

    return [r for r in results if r is not None]
