#!/usr/bin/env python3
"""Paired schematic/extracted preamp-noise feasibility probe (issue #202).

ONE nominal point (tt, 27 C, 3.30 V), run locally as three single-unit ngspice
`-b` runs (no grid, no loop over PVT points): this is a measurement-ACCESS
study, not a corner campaign. The 45-point extension is a follow-up that must
go through `klt sim` on the batch fleet (see the artifacts README).

WHAT IT DOES
------------
1. Re-extracts `layout/comparator.gds` with `klt extract --parasitics` into a
   scratch directory (the committed `layout/lvs/comparator.extract-rc.json` is
   NOT touched; the installed klt may differ from the one that minted it) and
   adapts it with `layout/run_extract_sim.py`'s own adaptation (unchanged).
2. Derives the preamp output nodes from the extracted CONNECTIVITY with
   `layout/pex/preamp_nodes.py` (fails closed; cross-checked against the
   extraction report). No net number is hard-coded.
3. Builds the paired deck: the SAME stimulus, reset state (clk = 0), bias
   (`dut_ib`, `dut_vcm` from sim/dut.json), fnoicor (PDK default 0), noise
   bands (1 Hz-1 GHz and 1 kHz-1 GHz), and the SAME methodology as
   `sim/comparator-preamp-noise/testbench/tb_preamp_noise.spice`
   (integrated output noise / measured DC gain), with the WHOLE comparator
   instantiated (`comparator_dut`) and the preamp outputs observed
   hierarchically at the defined points. No device or R/C is altered.
4. Runs ngspice and writes `record.json` plus the decks/logs.

The committed analog-partition bench and `sim/dut.json`'s refusal are not
modified. Reset-state `.noise` excludes the latch's regenerative noise.

Usage:  python3 layout/pex/preamp_noise_probe.py --outdir <dir>
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import math
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(REPO_ROOT, "sim"))
sys.path.insert(0, os.path.join(REPO_ROOT, "layout"))

import preamp_nodes  # noqa: E402

TB_SPICE = os.path.join(REPO_ROOT, "sim", "comparator-preamp-noise", "testbench",
                        "tb_preamp_noise.spice")
TB_JSON = os.path.join(REPO_ROOT, "sim", "comparator-preamp-noise", "testbench", "tb.json")
DUT_JSON = os.path.join(REPO_ROOT, "sim", "dut.json")
SCHEMATIC = os.path.join(REPO_ROOT, "design", "comparator.spice")
GDS = os.path.join(REPO_ROOT, "layout", "comparator.gds")

TEMP_C = 27.0
VDD = 3.3
#: Typical bundle, the harness's own `tt` corner (sim/harness/corners.py).
TT_SECTIONS = ("typical", "res_typical", "bjt_typical", "diode_typical",
               "moscap_typical", "mimcap_typical")
C_ROUTE_BENCH = "10f"  # the committed bench's stated routing allowance


def sha256(path: str) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def _load_extract_sim():
    spec = importlib.util.spec_from_file_location(
        "run_extract_sim", os.path.join(REPO_ROOT, "layout", "run_extract_sim.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _cmd(*argv: str) -> str:
    return subprocess.run(argv, capture_output=True, text=True, check=True).stdout.strip()


# --------------------------------------------------------------------------- #
# Deck
# --------------------------------------------------------------------------- #

def observation_points(label: str, nodes: dict, with_leg: bool) -> list[tuple[str, str, str]]:
    pts = [("hub", nodes["aop"]["hub"], nodes["aon"]["hub"])]
    if with_leg:
        pts.append(("drain_leg", nodes["aop"]["drain_leg"], nodes["aon"]["drain_leg"]))
    return pts


def build_deck(title: str, dut_include: str, pdk, obs: list[tuple[str, str, str]],
               c_route: str, c_nodes: tuple[str, str] | None, dut_params: dict,
               tie_vsubs: bool = False) -> str:
    L = [f"* {title} -- GENERATED by layout/pex/preamp_noise_probe.py (issue #202), do not edit",
         f".param vdd_nom={VDD!r}", f".param vdd_val={VDD!r}", f".param temp_c={TEMP_C!r}"]
    L += [f".param {k}={v!r}" for k, v in dut_params.items()]
    L += [f'.include "{pdk.design_include}"']
    L += [f'.lib "{pdk.model_lib}" {s}' for s in TT_SECTIONS]
    L += [f".temp {TEMP_C!r}", f'.include "{dut_include}"', "",
          "vsup vdd 0 dc {vdd_val}",
          "vcm  cm 0 dc {dut_vcm}",
          "vd   vd 0 dc 0 ac 1",
          "Eap  ap cm vd 0 0.5",
          "Ean  an cm vd 0 -0.5",
          "ib   vdd ibn dc {dut_ib}",
          "* the WHOLE comparator, held in reset (clk low)",
          "vclk clk 0 dc 0",
          "Xdut ap an clk ibn dout doutb vdd 0 comparator_dut"]
    if c_nodes and c_route != "0":
        L += [f"Cwp {c_nodes[0]} 0 {c_route}", f"Cwn {c_nodes[1]} 0 {c_route}"]
    if tie_vsubs:
        L += ["* SENSITIVITY ONLY: tie the extraction's global substrate node to 0 V.",
              "* The extraction ties it to 0 through 1e12 ohm, i.e. floating for AC.",
              "Vsubs_sens vsubs 0 dc 0"]
    L += ["", ".control", "set numdgt=10", "set noaskquit", "op"]
    for name, p, n in obs:
        L += [f"let dc_{name}_p = v({p})", f"let dc_{name}_n = v({n})"]
    L += ["let i_vsup_ua = abs(i(vsup))*1e6", "let vbias_anchor_mv = v(ibn)*1e3"]
    L += [f"print {n}" for n in ["i_vsup_ua", "vbias_anchor_mv"] + [
        f"dc_{o[0]}_{x}" for o in obs for x in "pn"]]
    plot = 1
    plots = {}
    for name, p, n in obs:
        L += [f"noise v({p},{n}) vd dec 20 1 1e9", f"noise v({p},{n}) vd dec 20 1e3 1e9"]
        # each `.noise` makes TWO plots: noise<odd> = spectra, noise<even> =
        # integrated totals (the committed tb.json reads noise2 / noise4).
        plots[name] = (plot, plot + 2)
        plot += 4
    L += ["ac dec 20 1 1e9"]  # the ac plot is current: v() below reads it
    for name, p, n in obs:
        a, b = plots[name]          # spectrum plots; totals are a+1 / b+1
        L += [f"let m_{name}_av_dc = mag(v({p})-v({n}))[0]",
              f"let m_{name}_onoise_uv = noise{a+1}.onoise_total*1e6",
              f"let m_{name}_onoise_hf_uv = noise{b+1}.onoise_total*1e6",
              f"let m_{name}_vn_in_uv = noise{a+1}.onoise_total/m_{name}_av_dc*1e6",
              f"let m_{name}_vn_in_hf_uv = noise{b+1}.onoise_total/m_{name}_av_dc*1e6",
              f"let m_{name}_inoise_band_uv = noise{a+1}.inoise_total*1e6",
              f"let m_{name}_white_nv_rthz = noise{a}.onoise_spectrum[120]*1e9",
              f"let m_{name}_enbw_mhz = (noise{a+1}.onoise_total^2)/(noise{a}.onoise_spectrum[120]^2)/1e6"]
    names = []
    for name, _, _ in obs:
        names += [
            f"m_{name}_{k}" for k in ("av_dc", "onoise_uv", "onoise_hf_uv", "vn_in_uv",
                                      "vn_in_hf_uv", "inoise_band_uv", "white_nv_rthz",
                                      "enbw_mhz")]
    L += [f"print {n}" for n in names]
    L += [".endc", ".end", ""]
    return "\n".join(L)


_VAL = re.compile(r"^\s*(\S+)\s*=\s*([-+0-9.eE]+)\s*$")


def parse_measures(text: str) -> dict[str, float]:
    vals: dict[str, float] = {}
    for line in text.splitlines():
        m = _VAL.match(line)
        if m:
            vals[m.group(1).lower()] = float(m.group(2))
    return vals


def run_ngspice(deck: str, deck_path: str, log_path: str) -> dict[str, float]:
    Path(deck_path).write_text(deck)
    proc = subprocess.run(["ngspice", "-b", "-o", log_path, deck_path],
                          capture_output=True, text=True, timeout=900)
    text = Path(log_path).read_text() if os.path.exists(log_path) else proc.stdout
    return parse_measures(text)


def check_finite_positive(vals: dict[str, float], obs_names: list[str]) -> list[str]:
    bad = []
    for name in obs_names:
        for k in ("av_dc", "onoise_uv", "onoise_hf_uv", "vn_in_uv", "vn_in_hf_uv"):
            v = vals.get(f"m_{name}_{k}")
            if v is None or not math.isfinite(v) or v <= 0:
                bad.append(f"{name}.{k}={v!r}")
    return bad


# --------------------------------------------------------------------------- #

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--outdir", required=True)
    args = ap.parse_args()
    out = os.path.abspath(args.outdir)
    os.makedirs(out, exist_ok=True)

    from harness.pdk import find_pdk
    pdk = find_pdk()
    duts = json.loads(Path(DUT_JSON).read_text())["duts"]
    params = duts["comparator-dr0001"]["params"]
    if params != duts["comparator-dr0001-layout"]["params"]:
        sys.exit("sim/dut.json: schematic and layout entries no longer share params")

    # --- extraction (scratch; committed report untouched) ---------------------
    res = _load_extract_sim()
    scratch = tempfile.mkdtemp(prefix="preamp-noise-")
    raw = os.path.join(scratch, "comparator.extracted-rc.spice")
    rep_path = os.path.join(scratch, "comparator.extract-rc.json")
    report = res.run_extract(raw, rep_path, parasitics=True)
    dut_layout = os.path.join(out, "comparator.dut-layout.cir")
    res._adapt_netlist(raw, dut_layout)
    res._check_interface_contract(dut_layout)

    # --- observation mapping (fail closed) -----------------------------------
    text = Path(dut_layout).read_text()
    try:
        mapping = preamp_nodes.derive(text)
        preamp_nodes.crosscheck_labels(mapping)
        preamp_nodes.crosscheck_report(mapping, report)
    except preamp_nodes.MappingError as e:
        sys.exit(f"OBSERVATION MAPPING FAILED: {e}")
    nodes_x = preamp_nodes.observation_nodes(mapping, "xdut.xlayout_dut")
    nodes_s = {k: {"hub": f"xdut.{k}", "drain_leg": f"xdut.{k}"} for k in ("aop", "aon")}

    # --- three single-point runs ---------------------------------------------
    cases = [
        ("schematic_bench_croute", SCHEMATIC, nodes_s, False, C_ROUTE_BENCH,
         (nodes_s["aop"]["hub"], nodes_s["aon"]["hub"])),
        ("schematic_croute0", SCHEMATIC, nodes_s, False, "0", None),
        ("extracted", dut_layout, nodes_x, True, "0", None),
        ("extracted_vsubs_tied", dut_layout, nodes_x, True, "0", None),
    ]
    results = {}
    for label, dut_path, nodes, leg, c_route, c_nodes in cases:
        tie = label.endswith("vsubs_tied")
        obs = observation_points(label, nodes, leg)
        deck = build_deck(label, dut_path, pdk, obs, c_route, c_nodes, params, tie)
        deck_path = os.path.join(out, f"{label}.cir")
        vals = run_ngspice(deck, deck_path, os.path.join(out, f"{label}.log"))
        bad = check_finite_positive(vals, [o[0] for o in obs])
        results[label] = {"values": vals, "invalid": bad, "c_route": c_route,
                          "dut_netlist": os.path.relpath(dut_path, REPO_ROOT)
                          if dut_path == SCHEMATIC else "comparator.dut-layout.cir",
                          "dut_sha256": sha256(dut_path), "deck_sha256": sha256(deck_path),
                          "observation_nodes": {o[0]: [o[1], o[2]] for o in obs}}

    record = {
        "issue": 202,
        "point": {"process": "tt", "temperature_c": TEMP_C, "vdd_v": VDD,
                  "fnoicor": 0, "mismatch": "off", "clk": "held low (reset)",
                  "dut_params": params},
        "identity": {
            "git_commit": _cmd("git", "-C", REPO_ROOT, "rev-parse", "HEAD"),
            "gds_sha256": sha256(GDS),
            "schematic_netlist_sha256": sha256(SCHEMATIC),
            "bench_reference_sha256": {"tb_preamp_noise.spice": sha256(TB_SPICE),
                                       "tb.json": sha256(TB_JSON)},
            "extract_netlist_sha256_raw": sha256(raw),
            "extract_report": {"netlist_sha256": report.get("netlist_sha256"),
                               "klt_version": (report.get("provenance") or {}).get("klt_version"),
                               "klayout_version": (report.get("provenance") or {}).get("klayout_version"),
                               "parasitics": {k: report["parasitics"].get(k) for k in (
                                   "r_count", "c_count", "cc_count", "distributed_rc",
                                   "total_resistance_ohm", "total_capacitance_ff")}},
            "klt": _cmd("klt", "--version"),
            "ngspice": _cmd("ngspice", "--version").splitlines()[1].strip(),
            "pdk": pdk.provenance(),
            "invocation": "python3 layout/pex/preamp_noise_probe.py --outdir "
                          "layout/pex/artifacts/preamp-noise",
        },
        "mapping": mapping,
        "observation_nodes_extracted": nodes_x,
        "results": results,
    }
    with open(os.path.join(out, "record.json"), "w") as f:
        json.dump(record, f, indent=1, sort_keys=True)
        f.write("\n")
    bad = {k: v["invalid"] for k, v in results.items() if v["invalid"]}
    print(json.dumps({k: {n: v["values"].get(n) for n in v["values"] if n.startswith("m_")}
                      for k, v in results.items()}, indent=1))
    if bad:
        print(f"FEASIBILITY: NOT finite-positive: {bad}", file=sys.stderr)
        return 3
    return 0


if __name__ == "__main__":
    sys.exit(main())
